project1_wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("newpage", views.newpage, name = "newpage"),
    path("random", views.random, name = "random"),
    path("wiki/<str:name>", views.article, name="article"),
    path("wiki/<str:name>/edit", views.edit, name = "edit"),
    path("search", views.search, name = "search"),
]

project1_wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1_wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1_wiki/encyclopedia/forms.py
from socket import fromshare
from django import forms

class AddPage(forms.Form):
    title = forms.CharField(label='Title', widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    text =  forms.CharField(label='Content', widget=forms.Textarea(
        attrs={'class': 'form-control'}
    ))

class EditPage(forms.Form):
    title = forms.CharField(label='Title', widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    text =  forms.CharField(label='Content', widget=forms.Textarea(
        attrs={'class': 'form-control', 'required':'False'}
    ))
    

project1_wiki/encyclopedia/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from markdown2 import markdown
from random import choice
from . import util
from .forms import AddPage, EditPage


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def article(request, name):
    if request.method == 'POST':
        return redirect('encyclopedia:edit', name = name)

    entry = util.get_entry(name)
    if entry:
        return render(request, "encyclopedia/article.html",{
            "title":name,
            "article": markdown(entry)
        })
    else:
        return render(request, "encyclopedia/article.html",{
            "article": "None"
        })


def newpage(request):
    if request.method == 'POST':
        form = AddPage(request.POST)
        if form.is_valid():
            # get post data
            title = form.cleaned_data["title"]
            content = form.cleaned_data["text"]

            # check if title already exists
            entries= util.list_entries()
            if title in entries:
                messages.error(request, f'ERROR: Page named {title} already exists.')
                return redirect('encyclopedia:newpage')

            else:
                # added Heading(Title) to the content
                # content = f'# {title}\n\n' + content

                # save md in entries
                try:
                    util.save_entry(title, content)
                    messages.success(request, 'Page added successfully')
                    return redirect('encyclopedia:article', name = title)
                # some error while saving
                except:
                    messages.error(request, f'Some error occured while creating {title} page.')
                    return redirect('encyclopedia:newpage')
                
        return redirect('encyclopedia:newpage')

    return render(request, "encyclopedia/newpage.html",{
        'form': AddPage(),
    }) 


def edit(request, name):

    if request.method == 'POST':
        form = EditPage(request.POST)
        
        if form.is_valid():
            # get post data
            title = form.cleaned_data["title"]
            content = form.cleaned_data["text"]

            # verify title
            if title == name:
                # check if title already exists
                entries= util.list_entries()
                if title not in entries:
                    messages.error(request, f'ERROR: Page named {title} doesn\'t exist.')
                    return redirect('encyclopedia:index')

                else:
                    # added Heading(Title) to the content
                    # content = f'# {title}\n\n' + content

                    # save md in entries
                    try:
                        util.save_entry(title, content)
                        messages.success(request, 'Page edited successfully')
                        return redirect('encyclopedia:article', name = title)
                    # some error while editing
                    except:
                        messages.error(request, f'Some error occured while editing {title} page.')
                        return redirect('encyclopedia:index')
            else:
                messages.error(request, f'Couldn\'t save edits because page named {title} doesn\'t exist.')
                return redirect('encyclopedia:index')
        else:
            messages.error(request, f'ERROR: Form invalid')
            return redirect('encyclopedia:index')

    else:
        entry = util.get_entry(name)
        form = EditPage()
        form.fields['title'].initial = name
        form.fields['text'].initial = entry
        
        if entry:
            return render(request, "encyclopedia/edit.html",{
                "title":name,
                "form": form,
            })
        else:
            messages.error(request, f'ERROR: Page Not Found')
            return redirect('encyclopedia:index')


def random(request):
    entries = util.list_entries()
    random_choice = choice(entries)
    return redirect('encyclopedia:article', name= random_choice)


def search(request):

    if request.method =='POST':
        q = request.POST.get('q').strip()
        entries = util.list_entries()
        if q:
            # check perfect match
            for entry in entries:
                if q.lower() == entry.lower():
                    return redirect('encyclopedia:article', name=entry)

            substrings=set()
            # check for substrings
            for entry in util.list_entries():
                if util.check_sub(entry, q):
                    substrings.add(entry)
                elif util.check_sub(q, entry):
                    substrings.add(entry)

            return render(request, 'encyclopedia/search.html', {
                'entries': sorted(substrings),
                'search': q
            })
    return render(request, 'encyclopedia/search.html')

project1_wiki/encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {% if article != 'None' %}
        {{title}}
    {% else %}
        Page Not Found
    {% endif %}

{% endblock %}

{% block body %}
    <div class='article'>
        {% if article != 'None' %}
            {{article|safe}}
            <div class='edit_btn'>
                <a href="{% url 'encyclopedia:edit' name=title %}" class="btn btn-outline-dark">Edit Page</a>
            </div>
        {% else %}
            <div class= 'article_message'>
                <h1>404: Page Not Found</h1>
            </div>
        {% endif %}
    </div>
{% endblock %}

project1_wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit: {{title}}
{% endblock %}

{% block body %}
    
    <h1>Edit {{title}}</h1>
    
    <form action = '{% url 'encyclopedia:edit' name=title %}' method = 'post'>
        {% csrf_token %}
        <label class ='col-sm-2 col-form-label col-form-label-lg'>{{form.title.label}}</label>
        <div class="col-sm-10">
            {{form.title}}
        </div>
        <label class ='col-sm-2 col-form-label col-form-label-lg'>{{form.text.label}}</label>
        <div class="col-sm-10">
            {{form.text}}
        </div>     
        
        <br>
        <div class="col-auto">
            <button type="submit" class="btn btn-outline-dark">Edit</button>
        </div>
    </form>
    <br>
    <div class="col-auto">
        <a href="{% url 'encyclopedia:article' name=title %}" class="btn btn-outline-dark">Cancel</a>
    </div>
{% endblock %}

project1_wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    
    <br>

    <ul class="list-group">
        {% for entry in entries %}
            <a class="list-group-item list-group-item-action" href='{% url 'encyclopedia:article' name=entry %}'>{{ entry }}</a>
        {% endfor %}
    </ul>

{% endblock %}

project1_wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- favicon and stylesheet-->
        <link rel="icon" href = "{% static 'encyclopedia/favicon.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <span class = 'navbar-brand mb-0 h1 nav-link'>Wiki</span>
                <br>
                
                <form action='{% url 'encyclopedia:search' %}' method = 'POST'>
                    {% csrf_token %}
                    <div class ="nav-link search_div">
                        <input class="search form-control" type="text" name="q" placeholder="Search Encyclopedia">
                    </div>
                </form>
                

                <div class ="nav-link">
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div class ="nav-link">
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div class ="nav-link">
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>

                {% block nav %}
                {% endblock %}
                
            </div>
            <div class="main col-lg-10 col-md-9">
                <div class="body_spacing">
                    
                    <div class= 'messages'>
                        {% for message in messages %}
                            {{message}}
                        {% endfor %}
                    </div>

                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>

    </body>
</html>

project1_wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia: Create New Page
{% endblock %}

{% block body %}
    
    <h1 class="col-sm-10">Create a New Page</h1>
    
    <form action = '{% url 'encyclopedia:newpage' %}' method = 'post'>
        {% csrf_token %}
        {% for field in form %}
        
        <label class ='col-sm-2 col-form-label col-form-label-lg'>{{field.label}}</label>
        <div class="col-sm-10">
            {{field}}
        </div>   
        
        {% endfor %}
        <br>
        <div class="col-auto">
            <button type="submit" class="btn btn-outline-dark">Submit</button>
        </div>
    </form>

{% endblock %}

project1_wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <br>
    
    {% if entries %}
    <ul class="list-group">
            {% for entry in entries %}
                <a class="list-group-item list-group-item-action" href='{% url 'encyclopedia:article' name=entry %}'>{{ entry }}</a>
            {% endfor %}
    </ul>
    {% elif search %}
        <h4>No records named '{{ search }}' found.</h4>
    {% else %}
        <h4>Enter the query in the field on the left column to search</h4>
    {% endif %}
        
{% endblock %}